version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    hostname: api
    network_mode: bridge
    environment:
      - PORT=3005
      - DB_HOST=postgres
      - DB_PORT=5433
      - DB_USER=postgres
      - DB_PASSWORD=adminadmin
      - DB_NAME=db
      - API_URL=http://api:3005
      - STAGE=DEV
    expose:
      - 3005
    ports:
      - 3005:3005
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres
    restart: always
    network_mode: bridge
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminadmin
      - POSTGRES_DB=db
    expose:
    - 5433
    ports:
      - 5433:5433
    command: -p 5433
