# Get all banks
GET http://localhost:3001/banks HTTP/1.1

Response:
[
  {
    "id": "string",
    "name": "string",
    "balance": 0
  }
]


# Get one bank by id
GET http://localhost:3001/banks/:id HTTP/1.1

Response:
{
  "id": "string",
  "name": "string",
  "balance": 0
}


# Create new bank
POST http:/localhost:3001/banks HTTP/1.1

Request: 
{
  "name": "string"
}

Response:
{
  "message": "string",
  "id": "string"
}


# Update bank
PUT http:/localhost:3001/banks/:id HTTP/1.1

Request: 
{
  "name": "string"
}

Response:
{
  "message": "string",
  "id": "string"
}

# Delete bank
DELETE http:/localhost:3001/banks/:id HTTP/1.1

Response:
{
  "message": "string",
  "id": "string"
}
