# Get all categories
GET http://localhost:3001/categories HTTP/1.1

Response:
[
  {
    "id": "string",
    "name": "string"
  }
]


# Get one category by id
GET http://localhost:3001/categories/:id HTTP/1.1

Response:
{
  "id": "string",
  "name": "string"
}


# Create new category
POST http:/localhost:3001/categories HTTP/1.1

Request: 
{
  "name": "string"
}

Response:
{
  "message": "string",
  "id": "string"
}


# Update category
PUT http:/localhost:3001/categories/:id HTTP/1.1

Request: 
{
  "name": "string"
}

Response:
{
  "message": "string",
  "id": "string"
}

# Delete category
DELETE http:/localhost:3001/categories/:id HTTP/1.1

Response:
{
  "message": "string",
  "id": "string"
}

