# Get all categories` statistic. *Date format: YYYY-MM-DD
POST http:/localhost:3001/statistics HTTP/1.1

Request: 
{
  "categoryIds": [
    "string"
  ],
  "fromPeriod": "YYYY-MM-DD",
  "toPeriod": "YYYY-MM-DD"
}

Response:
[
  {
    "categoryName": 0
  }
]
