# Create new transaction via webhook
POST http:/localhost:3001/webhooks/transactions HTTP/1.1

Request: 
{
  "amount": 0,
  "bankId": "string",
  "categoryIds": [
    "string"
  ]
}

Response:
{
  "message": "string"
}
